steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/lemur-broker', 'lemur-broker/' ]
  id: 'Build lemur-broker image'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/lemur-broker' ]
  id: 'Push lemur-broker image'
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'lemur-broker', '--image', 'gcr.io/$PROJECT_ID/lemur-broker', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated', '--set-env-vars', 'DRIVE_FOLDER_ID=1Zi9ejkrvwAOTlJm4VtEJBydWKHJgN8YF,API_ENDPOINT_URL=http://34.90.192.243/deman_gen_insights,PUBSUB_TOPIC=your-pubsub-topic' ]
  id: 'Deploy lemur-broker to Cloud Run'

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/lemur-generate', 'lemur-generate/' ]
  id: 'Build lemur-generate image'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/lemur-generate' ]
  id: 'Push lemur-generate image'
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'lemur-generate', '--image', 'gcr.io/$PROJECT_ID/lemur-generate', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated', '--set-env-vars', 'DRIVE_FOLDER_ID=1Zi9ejkrvwAOTlJm4VtEJBydWKHJgN8YF,API_ENDPOINT_URL=http://34.90.192.243/deman_gen_insights,PUBSUB_SUBSCRIPTION=your-pubsub-subscription,SLIDES_TEMPLATE_ID=your-template-id' ]
  id: 'Deploy lemur-generate to Cloud Run'
