steps:
  # Build the Docker image for the combined service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lemur-combined', '.']
    dir: './lemur-combined'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lemur-combined']

  # Deploy the combined service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud run deploy lemur-combined \
        --image gcr.io/$PROJECT_ID/lemur-combined \
        --platform managed \
        --region us-central1 \
        --allow-unauthenticated
timeout: '1800s'
